import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "../../Components/Header/Header";
import { Box } from "@mui/material";
import Footer from "../../Components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={{ margin: "0" }}>
        <Box sx={{ position: "fixed", width: "100%" }} id="Content Header">
          <Header />
        </Box>
        {children}
        <Footer />
      </body>
    </html>
  );
}
